### ISSUE TITLE
A question about the argument in mse_loss

### ISSUE THREAD

**Issue by VincentWanghh** [irom-lab/dppo#14]
Hi @allenzren , thank you for this excellent work and for making such a high-quality codebase. I am a freshman in diffusion model and your code really helps me a lot!

But I have a question in ```model/diffusion/diffusion.py```.  That is, in this [line](https://github.com/irom-lab/dppo/blob/4e14b8086d29e86e172a6dde4a20f428d96c702b/model/diffusion/diffusion.py#L319),why does it need to
```return F.mse_loss(x_recon, x_noisy, reduction="mean")```
instead of 
```return F.mse_loss(x_recon, x_start, reduction="mean")```?
I have checked [diffusion.py](https://github.com/jannerm/diffuser/blob/main/diffuser/models/diffusion.py) in [Diffuser](https://github.com/jannerm/diffuser), and it seems to use [the latter one](https://github.com/jannerm/diffuser/blob/7ea422860cc0106e5ca5949d980f04b799d5462c/diffuser/models/diffusion.py#L222)?

Thanks!

**Comment by allenzren** [comment]
Ah that is a bug --- we started by predicting `x_start` at the beginning of the project, and then switched to predict epsilon instead. At one point we made the bug. Fixed now, thanks very much for pointing it out!

Btw, is there any particular reason you want to predict `x_start` instead of `x_noisy` in your application?

**Comment by VincentWanghh** [comment]
Thanks for your reply!

I am learning diffusion model so I want to see the effect of this two different prediction methods :)
