### ISSUE TITLE
Possible bug introduced in commit (2ddf63b)

### ISSUE THREAD

**Issue by acl21** [irom-lab/dppo#5]
Hi @allenzren, firstly, thank you for such a nicely written code repository.

I suspect you introduced a bug in your recent commit `2ddf63b`. You can see [here](https://github.com/irom-lab/dppo/blob/64595baca9d6c42af332eb17b97f91febda6f6f5/model/diffusion/diffusion.py#L212) that the `forward` function of `model.diffusion.diffusion.DiffusionMLP` is not implemented anymore. 

Is this expected behaviour? 

Thanks in advance.

**Comment by allenzren** [comment]
Hi @acl21, thanks for the message. I had a major refactor of the code last week to add some new functionalities, and also I cleaned up the code a bit. I deprecated the `forward` function in the `Diffusion` class since the code never uses the base class for running the policy inference. If you are running DPPO, the `forward` function should be the one [here](https://github.com/irom-lab/dppo/blob/64595baca9d6c42af332eb17b97f91febda6f6f5/model/diffusion/diffusion_vpg.py#L241). Does this make sense?

I guess one might want to evaluate the pre-trained policy only, but that can also be done with running the fine-tuning script for one iteration only (the first iteration is running eval).

Btw it is `model.diffusion.diffuion.Diffusion`, not `model.diffusion.diffusion.DiffusionMLP`

**Comment by acl21** [comment]
Ah, that makes sense. Yes, indeed, I wanted to evaluate a pre-trained policy (on a different dataset - CALVIN). Thank you for the quick clarification.

**Comment by allenzren** [comment]
Cool, yea I think running eval with a separate script would be helpful. Let me add the implementation so it would be easier to run eval and also avoid the GPU overhead from making copy of the policy, for example.

**Comment by allenzren** [comment]
I just added the evaluation agents and re-implemented `forward` in the base diffusion class for running eval. See c9f24ba0c3f9092c000830a10004453bc40886d3
